### ISSUE TITLE
Move data processing into evaluatR.init

### ISSUE THREAD

**Issue by weinbergerlab** [weinbergerlab/InterventionEvaluatR#10]
currently data processing (formatting covariates etc) is done in the evaluatr.impact function. However it would be desirable to have the time series processed independently. This way, the data would be available for other functions (ie simple ITS, single variable GLMER) withou having to first run the computationally costly.impact function

**Comment by innermatrix** [comment]
The data processing is in `evaluatr.impact.pre` and is called by impact analysis — and now also univariate analysis.
