### ISSUE TITLE
X axis labels for some `epi_year` plots are unhelpful

### ISSUE THREAD

**Issue by innermatrix** [weinbergerlab/InterventionEvaluatR#3]
With year_def set to `epi_year`, X axis labels coming out of `plotPredAgg` end up being 1…N rather than actual years. We should map `ann_pred_quantiles$year` back to calendar years when plotting.

**Comment by weinbergerlab** [comment]
On same vein, I think the vertical line indicating vaccine introduction is being place at the wrong place on the summary plots when using epi_year, which confuses the results.
